language: go

go:
  - 1.4
  - 1.5.1

install:
  - export PATH=$GOPATH/bin:./_tools/etcd/bin:$PATH
  - make install-travis

deploy:
  provider: s3
  access_key_id: AKIAO27MPEIWV3GJ56EQ
  secret_access_key:
    secure: T3EESo1TJM1FcwOs2Zeo9SswuW1EigALAjIwc5d5OJJIBA/SMrUDVCjYehxxM3n2s+k3dyOTu7DTX9M2RN1EAjvBr/Kt0Ci7ZcKqpKaQXr/Ij3zer3qWKMbXQAxZbOkm7Ywuy2VM/p8rn4me8IKI2eqqvZnVrUWN7JXEyLG5Wm1lvl4JTF3eR80dgmceMhv17JyU3XaBMkF1B4g29uuFfwmpwBUlbgHeE4HfVckFDnAII/3yYwiOUSoMwTtXKmqaZzJ+uTCoRb1W7As714ZqtDCHScYINOOmWlWpHrD5lJG3e0/kLB2syFEBRKzPPGQsLdP/sfhhF0OO8x1H4eze69Ur33XqGrVK6/OXxLRXL1kqklZ7MWtNOHJUJ7rtAkYcYay50iqV9tnyHzH3+9Ah6ErG9d0lM3Ui0QZiKLHtIiKDybjdU6mQn0jYQ6r28mj3NWWme41Ubk9MHq4qbpB5/kFnC5gzhyYTNvGW8d8LquADjtETZkbV1Gf3oBpMtkkevMjG4yIkEWx0xrglQYopUldzx/NLHFAi18Nodb0G0vq1TCr7uh/mcdbCFbbpCEqA3c+bKc375YXwGmajPSsFecjdokxBV22tc1lnA+6TQ+ngwS+MsUhMAcw0zXKxEfwPBJF1bDc26MnKHNyOrVDIaeJZSqiopbJw8cnUxjL9rUc=
  bucket: asiainfo-datafactory-bin
  upload-dir: dev-san
  local-dir: "_output/local/bin/linux/amd64"
  region: cn-north-1
  skip_cleanup: true
  
sudo: false
